name: NiftySense
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.70.2
  universal_platform: ^1.0.0+1
  path_provider: ^2.0.8 
  mysql1: ^0.20.0
  bcrypt: ^1.0.0 
  table_calendar: ^3.0.2



  http: ^0.13.6  # Downgrade to a compatible version
  intl: ^0.20.2
  provider: ^6.0.3
  syncfusion_flutter_gauges: ^29.1.33
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1 # Fixed version

flutter:
  uses-material-design: true

  assets:
    - assets/nifty50.jpg  # Ensure correct indentation and no extra spaces
    - assets/background1.jpg
    - assets/background2.jpg
    - assets/background3.jpg
    - assets/background4.jpg
    - assets/background5.jpg
    - assets/background6.jpg
    - assets/background7.jpg
    - assets/background8.jpg
    - assets/background9.jpg
    - assets/content.json